# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

matrix:
  include:
    #- os: linux
    #  python: 3.5
    #  env:
    #    - PYTHON_VER=3.5
    - os: linux
      python: 3.6
      env:
        - PYTHON_VER=3.6
    #- os: linux
    #  #python: 3.7
    #  env:
    #    - PYTHON_VER=3.7

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

  # Setup python environment
  - source devtools/travis-ci/before_install.sh
  - python -V

install:
    # Create test environment for package
  - python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/base.yaml
  - source activate test

    # Extra upstream for testing
  - conda install qcengine=0.6.4
  - conda install ci-psi4 psi4 -c psi4/label/dev

    # Build and install package
  - python setup.py develop --no-deps

before_script:
  - python -V
  - conda list

script:
  - pwd
  - cd tests
  - export PYTHONPATH=..:optking:.:tests

    # Get a bit of info first
  - python -c "import optking; print(optking.__version__)"

    # Run canonical tests (not quite b/c testing source, not install)
  - pytest -v -rws --durations=5 --cov

notifications:
    email: false

after_success:
  - codecov


#  - conda create -q -n tenv ci-psi4 psi4  -c psi4/label/dev
#  - conda install pytest qcelemental>=0.1.2 #pytest-cov codecov -c conda-forge
#  - pip install -e .
